const DUE_DATE = new Date('2026-05-29');

// Baby size comparisons by week (weeks 4-42)
const BABY_SIZES = {
  4:  { emoji: '🌰', name: 'Poppy Seed', length: '0.04 in', weight: '' },
  5:  { emoji: '🫘', name: 'Sesame Seed', length: '0.05 in', weight: '' },
  6:  { emoji: '🫐', name: 'Sweet Pea', length: '0.25 in', weight: '' },
  7:  { emoji: '🫐', name: 'Blueberry', length: '0.5 in', weight: '' },
  8:  { emoji: '🍇', name: 'Raspberry', length: '0.6 in', weight: '0.04 oz' },
  9:  { emoji: '🫒', name: 'Green Olive', length: '0.9 in', weight: '0.07 oz' },
  10: { emoji: '🍓', name: 'Strawberry', length: '1.2 in', weight: '0.14 oz' },
  11: { emoji: '🫐', name: 'Fig', length: '1.6 in', weight: '0.25 oz' },
  12: { emoji: '🍋', name: 'Lime', length: '2.1 in', weight: '0.5 oz' },
  13: { emoji: '🍋', name: 'Lemon', length: '2.9 in', weight: '0.81 oz' },
  14: { emoji: '🍑', name: 'Peach', length: '3.4 in', weight: '1.5 oz' },
  15: { emoji: '🍎', name: 'Apple', length: '4 in', weight: '2.5 oz' },
  16: { emoji: '🥑', name: 'Avocado', length: '4.6 in', weight: '3.5 oz' },
  17: { emoji: '🍐', name: 'Pear', length: '5.1 in', weight: '5 oz' },
  18: { emoji: '🫑', name: 'Bell Pepper', length: '5.6 in', weight: '6.7 oz' },
  19: { emoji: '🥭', name: 'Mango', length: '6 in', weight: '8.5 oz' },
  20: { emoji: '🍌', name: 'Banana', length: '6.5 in', weight: '10.6 oz' },
  21: { emoji: '🥕', name: 'Carrot', length: '10.5 in', weight: '12.7 oz' },
  22: { emoji: '🌽', name: 'Ear of Corn', length: '10.9 in', weight: '15.2 oz' },
  23: { emoji: '🥭', name: 'Large Mango', length: '11.4 in', weight: '1.1 lb' },
  24: { emoji: '🌽', name: 'Corn on the Cob', length: '11.8 in', weight: '1.3 lb' },
  25: { emoji: '🥦', name: 'Cauliflower', length: '13.6 in', weight: '1.5 lb' },
  26: { emoji: '🥬', name: 'Lettuce Head', length: '14 in', weight: '1.7 lb' },
  27: { emoji: '🥒', name: 'Cucumber', length: '14.4 in', weight: '1.9 lb' },
  28: { emoji: '🍆', name: 'Eggplant', length: '14.8 in', weight: '2.2 lb' },
  29: { emoji: '🎃', name: 'Acorn Squash', length: '15.2 in', weight: '2.5 lb' },
  30: { emoji: '🥬', name: 'Cabbage', length: '15.7 in', weight: '2.9 lb' },
  31: { emoji: '🥥', name: 'Coconut', length: '16.2 in', weight: '3.3 lb' },
  32: { emoji: '🍍', name: 'Pineapple', length: '16.7 in', weight: '3.7 lb' },
  33: { emoji: '🍍', name: 'Pineapple', length: '17.2 in', weight: '4.2 lb' },
  34: { emoji: '🍈', name: 'Cantaloupe', length: '17.7 in', weight: '4.7 lb' },
  35: { emoji: '🍈', name: 'Honeydew Melon', length: '18.2 in', weight: '5.3 lb' },
  36: { emoji: '🥬', name: 'Romaine Lettuce', length: '18.7 in', weight: '5.8 lb' },
  37: { emoji: '🧅', name: 'Swiss Chard Bunch', length: '19.1 in', weight: '6.3 lb' },
  38: { emoji: '🍉', name: 'Mini Watermelon', length: '19.6 in', weight: '6.8 lb' },
  39: { emoji: '🍉', name: 'Small Watermelon', length: '20 in', weight: '7.3 lb' },
  40: { emoji: '🍉', name: 'Watermelon', length: '20.2 in', weight: '7.6 lb' },
  41: { emoji: '🍉', name: 'Watermelon', length: '20.4 in', weight: '7.9 lb' },
  42: { emoji: '🍉', name: 'Large Watermelon', length: '20.5 in', weight: '8.1 lb' },
};

// Weekly milestones/developments
const MILESTONES = {
  4:  ['Heart begins to form', 'Neural tube developing', 'Tiny buds for arms and legs appear'],
  5:  ['Heart starts beating', 'Brain is growing rapidly', 'Facial features beginning to form'],
  6:  ['Nose, mouth, and ears take shape', 'Intestines developing', 'Brain waves detectable'],
  7:  ['Hands and feet emerging', 'Liver producing red blood cells', 'Appendix and pancreas forming'],
  8:  ['Fingers and toes forming', 'Baby starts making tiny movements', 'Taste buds developing'],
  9:  ['Muscles forming', 'Heart fully developed with 4 chambers', 'Reproductive organs developing'],
  10: ['Vital organs fully formed', 'Tiny tooth buds appearing', 'Fingernails starting to grow'],
  11: ['Baby can open and close fists', 'Tooth buds continue forming', 'Almost fully formed'],
  12: ['Reflexes developing', 'Intestines move into abdomen', 'Vocal cords forming'],
  13: ['Fingerprints forming', 'Veins visible through skin', 'Organs visible through thin skin'],
  14: ['Brain impulses firing', 'Facial muscles working — can squint and frown', 'Can suck thumb'],
  15: ['Can sense light', 'Skeleton hardening from cartilage to bone', 'Forming taste buds'],
  16: ['Circulatory system working', 'Umbilical cord fully mature', 'Toenails growing'],
  17: ['Fat stores beginning', 'Can hear your heartbeat', 'Sweat glands developing'],
  18: ['Ears in final position', 'Myelin coating nerves', 'Can yawn and hiccup'],
  19: ['Vernix coating forming', 'Brain designating areas for senses', 'Arms and legs proportional'],
  20: ['Halfway there!', 'Swallowing more and producing meconium', 'Can hear sounds outside the womb'],
  21: ['Eyebrows and eyelids formed', 'Liver and spleen producing blood cells', 'Coordinated movements'],
  22: ['Eyes formed but iris lacks color', 'Pancreas steadily developing', 'Lips becoming more distinct'],
  23: ['Skin is wrinkled and translucent', 'Rapid weight gain begins', 'Can hear your voice clearly'],
  24: ['Lungs developing branches', 'Taste buds fully developed', 'Real hair growing on head'],
  25: ['Baby responds to your voice', 'Nostrils opening', 'Spine forming joints and structures'],
  26: ['Eyes opening for first time', 'Lungs producing surfactant', 'Brain wave activity increasing'],
  27: ['Can open and close eyes', 'Regular sleep cycles forming', 'Brain is very active'],
  28: ['Can blink and dream (REM sleep)', 'Billions of neurons developing', 'Can recognize your voice'],
  29: ['Muscles and lungs maturing', 'Head growing to make room for brain', 'Bones fully developed but still soft'],
  30: ['Surroundings visible through uterine wall', 'Bone marrow producing red blood cells', 'Baby practicing breathing movements'],
  31: ['Brain connections forming rapidly', 'Can process information and track light', 'All five senses working'],
  32: ['Toenails visible', 'Practicing breathing', 'Skin becoming less transparent'],
  33: ['Bones hardening', 'Skull remains flexible for delivery', 'Immune system developing'],
  34: ['Lungs nearly mature', 'Central nervous system maturing', 'Fat layers filling out body'],
  35: ['Kidneys fully developed', 'Liver can process waste', 'Arms and legs getting chubby'],
  36: ['Gaining about an ounce a day', 'Skin is smooth and soft', 'Digestive system ready'],
  37: ['Considered early term', 'Lungs are mature', 'Baby is practicing inhaling and exhaling'],
  38: ['Brain and lungs continue maturing', 'Firm grasp', 'Organs ready for life outside'],
  39: ['Full term!', 'Brain still developing rapidly', 'Chest is more prominent'],
  40: ['Due date week!', 'Skull bones not fused for delivery', 'Ready to meet the world'],
  41: ['Post-term — still normal', 'Nails may be long', 'Very alert and ready'],
  42: ['Doctor will likely induce', 'Fully developed and ready', 'Skin may be dry and peeling'],
};

// Default chores/tasks to prepare for baby
const DEFAULT_CHORES = [
  { text: 'Set up the nursery', done: false },
  { text: 'Buy a car seat', done: false },
  { text: 'Pack hospital bag', done: false },
  { text: 'Wash baby clothes', done: false },
  { text: 'Install car seat base', done: false },
  { text: 'Stock up on diapers and wipes', done: false },
  { text: 'Choose a pediatrician', done: false },
  { text: 'Set up baby monitor', done: false },
  { text: 'Prepare freezer meals', done: false },
  { text: 'Create birth plan', done: false },
  { text: 'Tour the hospital/birth center', done: false },
  { text: 'Take infant CPR class', done: false },
];
